"""
Tiny Hive JSON-RPC client. Used when local MongoDB doesn't have a video's title
yet (e.g. embed videos before the hive_lookup sync runs, or legacy docs with
an empty title field).
"""

import json
import logging
import re
from typing import Any, Dict, Optional

import requests

logger = logging.getLogger(__name__)

# Embed-video docs sometimes carry the Hive reference in `embed_url` (form: "@author/permlink")
# even when `hive_permlink` is null. Parsing it lets us still fetch the post title.
_EMBED_URL_RE = re.compile(r'^@([a-z0-9.\-]+)/([a-z0-9.\-]+)$', re.IGNORECASE)

# Filenames that aren't worth using as titles: pure numbers, very short, IMG_*, VID_*, etc.
_BAD_FILENAME_RE = re.compile(r'^(?:\d+|[a-z]{1,4}|img[_\- ]?\d+|vid[_\- ]?\d+|movie\d*|untitled\d*)$', re.IGNORECASE)

# embed_title values we should treat as missing rather than real titles
_GENERIC_EMBED_TITLES = {'comment', 'untitled', 'new video', 'video'}


def parse_embed_url(embed_url: str):
    """If embed_url is "@author/permlink", return (author, permlink). Else (None, None)."""
    if not embed_url:
        return None, None
    m = _EMBED_URL_RE.match(embed_url.strip())
    return (m.group(1), m.group(2)) if m else (None, None)


def filename_to_title(filename: str) -> str:
    """Turn a file name into a usable title, or '' if it looks autogenerated."""
    if not filename:
        return ''
    base = re.sub(r'\.[a-zA-Z0-9]{2,5}$', '', filename).strip()
    base = re.sub(r'\s+', ' ', base.replace('_', ' ').replace('-', ' '))
    if not base or _BAD_FILENAME_RE.match(base.replace(' ', '')):
        return ''
    return base


def is_generic_title(title: str) -> bool:
    return (title or '').strip().lower() in _GENERIC_EMBED_TITLES

HIVE_NODES = (
    'https://api.hive.blog',
    'https://hived.privex.io',
    'https://api.openhive.network',
)

_title_cache: dict = {}
_post_cache: dict = {}


def _rpc_get_content(author: str, permlink: str, timeout: int) -> Optional[Dict[str, Any]]:
    """condenser_api.get_content across the node list. None if every node fails."""
    for node in HIVE_NODES:
        try:
            resp = requests.post(
                node,
                json={
                    'jsonrpc': '2.0',
                    'method': 'condenser_api.get_content',
                    'params': [author, permlink],
                    'id': 1,
                },
                timeout=timeout,
            )
            result = (resp.json() or {}).get('result') or {}
            # A missing post comes back as a doc with an empty author.
            if result.get('author'):
                return result
        except Exception as e:
            logger.debug(f"Hive node {node} failed for @{author}/{permlink}: {e}")
            continue
    return None


def fetch_hive_post(author: str, permlink: str, timeout: int = 10) -> Optional[Dict[str, Any]]:
    """
    Fetch title, body, tags and community for a Hive post. Cached per-process.

    Returns None when the post cannot be fetched, so callers can tell "no post"
    apart from "post with no tags".
    """
    if not author or not permlink:
        return None
    key = f"@{author}/{permlink}"
    if key in _post_cache:
        return _post_cache[key]

    result = _rpc_get_content(author, permlink, timeout)
    if result is None:
        return None

    tags = []
    try:
        meta = json.loads(result.get('json_metadata') or '{}')
        raw = meta.get('tags') or []
        if isinstance(raw, list):
            tags = [str(t) for t in raw if t]
    except (ValueError, TypeError):
        logger.debug(f"Unparseable json_metadata for {key}")

    post = {
        'title': (result.get('title') or '').strip(),
        'body': result.get('body') or '',
        'tags': tags,
        'category': (result.get('category') or '').strip(),
    }
    _post_cache[key] = post
    return post


def _body_to_title(body: str, max_len: int = 140) -> str:
    """Clean a post body into a title-sized excerpt (for waves/microblog posts)."""
    if not body:
        return ''
    # Markdown: drop image syntax, unwrap link text
    body = re.sub(r'!\[[^\]]*\]\([^)]+\)', ' ', body)
    body = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', body)
    # Strip HTML tags and URLs
    body = re.sub(r'<[^>]+>', ' ', body)
    body = re.sub(r'https?://\S+', ' ', body)
    body = re.sub(r'\s+', ' ', body).strip()
    if not body:
        return ''
    if len(body) > max_len:
        # Cut at a sentence boundary if there's one in a reasonable spot
        for m in re.finditer(r'[.!?](?:\s|$)', body):
            if 40 <= m.end() <= max_len:
                return body[:m.end()].strip()
        # Otherwise word-truncate with an ellipsis
        body = body[:max_len].rsplit(' ', 1)[0].rstrip() + '…'
    return body


def fetch_hive_title(author: str, permlink: str, timeout: int = 10) -> str:
    """
    Fetch a post title from Hive. For posts with no title (waves / microblog),
    falls back to a cleaned excerpt of the body. Cached per-process.
    """
    if not author or not permlink:
        return ''
    key = f"@{author}/{permlink}"
    if key in _title_cache:
        return _title_cache[key]
    for node in HIVE_NODES:
        try:
            resp = requests.post(
                node,
                json={
                    'jsonrpc': '2.0',
                    'method': 'condenser_api.get_content',
                    'params': [author, permlink],
                    'id': 1,
                },
                timeout=timeout,
            )
            data = resp.json()
            result = data.get('result') or {}
            title = (result.get('title') or '').strip()
            if title:
                _title_cache[key] = title
                return title
            body_title = _body_to_title(result.get('body') or '')
            if body_title:
                _title_cache[key] = body_title
                return body_title
        except Exception as e:
            logger.debug(f"Hive node {node} failed for {key}: {e}")
            continue
    _title_cache[key] = ''
    return ''
